### ISSUE TITLE
BTCPay Server throwing 502 Bad Gateway error since v0.2.52/0.2.53

### ISSUE THREAD

**Issue by brettjdicioccio** [mynodebtc/mynode#639] opened 2022-03-10 19:07 UTC
I have a very vanilla/stock myNode with default configs. I have been using BTCPay Server for a while now and all of the sudden after upgrading myNode to v0.2.52 I first noticed that a 502 Bad Gateway error is happening when navigating to mynode.local:49393. I saw that there was another myNode version that I could upgrade to v0.2.53. I upgraded assuming there would be a fix, but the issue still exists.

None of my configs are custom, everything is stock. I have attempted to hard reset my node by powering it down and turning it back on.

I noticed in the upgrade changelogs the following (so the BTCPay Server versions have been upgraded) :

=== v0.2.53 ===
- Released: 03/07/22
- Upgrade BTCPay Server to v1.4.7

=== v0.2.52 ===
- Released: 02/11/22
- Upgrade BTCPay Server to v1.4.4

I also noticed the following in the BTCPay Server logs, but not sure if it means anything is wrong:
Mar 10 12:51:40 myNode wait_on_lnd.sh[3615]: LND not synced, sleeping for 60 seconds...
Mar 10 12:51:40 myNode wait_on_lnd.sh[3615]: [lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

One last thing to mention is that I have a mesh network at home with a main router and a single satellite. The node used to be plugged into an ethernet port on the satellite, but I recently moved it and plugged into an ethernet port on the main router. I double checked that the LAN IP is still the same and it is. I don't see how this could be causing the problem, but figured I would mention it.

**Comment by tehelsper** [comment] 2022-03-11 03:51
I doubt moving the node caused any of these issues. Are you running 32-bit or 64-bit on your Pi? You can check on the settings page.

This issue has happened to some people and I'm now seeing it on one of my Pis (32-bit). I've logged an issue with BTC Pay to see if they can help.

Finally, is LND running? That log indicated BTCPay isn't starting because LND has not yet started.

**Comment by brettjdicioccio** [comment] 2022-03-11 03:58
I am unable to find 32-bit or 64-bit anywhere on the settings page. I went into the terminal and this is what I am getting: Linux myNode 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux

LND is showing as running with a green icon

Can I downgrade for now by adding the following to custom application versions?
BTCPAYSERVER_VERSION="1.3.7"

**Comment by tehelsper** [comment] 2022-03-11 04:28
Thanks. That's 32-bit. In those details armv7 = 32-bit and aarch64 (not shown) would be 64-bit.

Yeah, use that line to downgrade.

**Comment by brettjdicioccio** [comment] 2022-03-11 04:53
The downgrade worked however it is asking me to create a new account. Did I just lose everything on my previous BTCPayServer by doing this?

**Comment by tehelsper** [comment] 2022-03-14 22:33
That could be an error, but it could also be caused by the containers themselves crashing. I've found an error as well where an old Postgres version could be referenced causing it to not start properly. I've got a code fix for that locally, but it still doesn't work fully.

I've also found that the 32-bit btcpayserver container crashes right after launching and the 64-bit container does not. I'm thinking there could be a problem with that container on armv7 architecture. I added a comment to the issue I had logged.

More info: https://github.com/btcpayserver/btcpayserver/issues/3528

**Comment by as-schug** [comment] 2022-03-15 18:46
This error shows when we install btcpayserver

Maybe it helps

![image](https://user-images.githubusercontent.com/67750682/158449218-d3a3219c-cedd-419a-8caf-7ebface060ae.png)

**Comment by tehelsper** [comment] 2022-03-15 23:36
Thanks, I think that should be fixed as well with my changes, but I have not added them since the issue still isn't completely resolved. I could add them a push a beta to see if it helps you.

**Comment by tehelsper** [comment] 2022-03-16 04:49
I pushed a new beta. It may help with a some of the issues, but the root cause is likely still around.

**Comment by brettjdicioccio** [comment] 2022-03-16 04:53
@tehelsper Thank you! Is it safe to say all of my BTCPay Server data is gone from downgrading though? I just want to know so I can put this to rest. I've been using it for a few months now with the latest version, but after this bug was introduced I downgraded to see if I could still use it and it completely reset everything. I believe BTCPay Server relies on a BTCPay Docker Image and a Postgres Docker Image. When downgrading, it looks like they were both completely overwritten without backups or anything.

**Comment by as-schug** [comment] 2022-03-16 15:40
> @tehelsper Thank you! Is it safe to say all of my BTCPay Server data is gone from downgrading though? I just want to know so I can put this to rest. I've been using it for a few months now with the latest version, but after this bug was introduced I downgraded to see if I could still use it and it completely reset everything. I believe BTCPay Server relies on a BTCPay Docker Image and a Postgres Docker Image. When downgrading, it looks like they were both completely overwritten without backups or anything. I just removed the downgrade line from my custom application versions config and let it go back to the latest with the 502 bad gateway. Curious if my data will still be there somehow.

Yes. Every upgrade / downgrade resets all data...
So I backup postgres database before upgrading and restore it manually

**Comment by tehelsper** [comment] 2022-03-17 03:42
Upgrades should not lose data and I'm not familiar with the internal upgrade / downgrade procedures internal to BTC Pay Server. To upgrade, myNode swaps the containers out for new versions without changing any of the internal data. I could see downgrades possibly losing data since it may not understand new data formats, etc...

Have you lost data on upgrades? Like going from 1.3.x to 1.3.x+1?

**Comment by as-schug** [comment] 2022-03-17 11:46
> Upgrades should not lose data and I'm not familiar with the internal upgrade / downgrade procedures internal to BTC Pay Server. To upgrade, myNode swaps the containers out for new versions without changing any of the internal data. I could see downgrades possibly losing data since it may not understand new data formats, etc...
> 
> Have you lost data on upgrades? Like going from 1.3.x to 1.3.x+1?

Yes... It does lost data, for every upgrade...

**Comment by Trabbtc** [comment] 2022-03-23 10:13
I am also getting this error.
Is there a timeframe for this to be resolved?

Thanks!

**Comment by tehelsper** [comment] 2022-03-24 04:28
Sorry, I'm still investigating when I can. Reverting to 1.3.6 via customizing the app version seems to resolve for most people. I have also heard from users that the issue can be seen on 32-bit and 64-bit versions of their RP4 OS. (I have not heard of seeing it on other platforms yet)

To set a specific version, add this to your custom app version page. Go to Settings -> Customize App Versions.

BTCPAYSERVER_VERSION="1.3.6"

**Comment by motolese** [comment] 2022-04-01 06:12
Any news about this?

**Comment by tehelsper** [comment] 2022-04-03 02:33
Sorry, no news. There is a workaround to go back to 1.3.6 which does work.

**Comment by ArbenKarb** [comment] 2022-04-06 12:02
Unfortunately going back to 1.3.6 doesn't work for me.

**Comment by tehelsper** [comment] 2022-04-07 00:10
What happens when you got back to 1.3.6?

**Comment by ArbenKarb** [comment] 2022-04-07 11:26
Will probably try.

FYI, upgraded to V. 1.4.9 now the btcpayserver web interface resolves but the error that nbxplorer sync is a blockheight 0 occurs

**Comment by as-schug** [comment] 2022-04-08 13:36
![image](https://user-images.githubusercontent.com/67750682/162446682-d3724c8b-e46c-4c96-89a8-1b58e3210f57.png)

After upgrade, the problem still there

**Comment by as-schug** [comment] 2022-04-08 13:50
To downgrade, set those version

BTCPAYSERVER_VERSION="1.3.6"
BTCPAYSERVER_NBXPLORER_VERSION="2.2.18"

![image](https://user-images.githubusercontent.com/67750682/162449226-dc1abdd1-c957-4cc0-a248-bc639f2493e7.png)

**Comment by ArbenKarb** [comment] 2022-04-11 18:43
> To downgrade, set those version
> 
> BTCPAYSERVER_VERSION="1.3.6"
> BTCPAYSERVER_NBXPLORER_VERSION="2.2.18"
> 
> ![image](https://user-images.githubusercontent.com/67750682/162449226-dc1abdd1-c957-4cc0-a248-bc639f2493e7.png)
> 
> 
> 

Still doesn't work for me

**Comment by tehelsper** [comment] 2022-04-12 01:46
@ArbenKarb Can you give it a minute and try to access it again. Your issue is likely different - that screenshot shows all containers running properly.

**Comment by ArbenKarb** [comment] 2022-04-12 13:04
Manually downgraded to:

BTCPAYSERVER_VERSION="1.3.6"
BTCPAYSERVER_NBXPLORER_VERSION="2.2.18"

Still get this (no progress)

![grafik](https://user-images.githubusercontent.com/31412198/162968440-76ea6f8c-a8ed-4735-bd41-dbfaa50be2dc.png)

![grafik](https://user-images.githubusercontent.com/31412198/162968712-3e6eb889-8118-4ea3-b4b0-648a582e9cf2.png)

**Comment by tehelsper** [comment] 2022-04-14 04:08
I have found several issues with the BTCPay deployment on recent versions. I'm not sure if it resolves the issues on ARM32 yet, but it could be better. I just published a beta with a large number of improvements and should definitely resolve the issue from @ArbenKarb.

Can you try installing the beta and report back? You _may_ need to re-install BTCPay server if it doesn't help right away.

Also, a BTCPay "uninstall" will now also remove the docker volume and reset all data. A "reinstall" will not.

**Comment by ArbenKarb** [comment] 2022-04-14 05:00
Sure, where can I download the beta?

**Comment by tehelsper** [comment] 2022-04-14 05:05
Bottom of the settings page in the "Developer" section. You may need to click "Check for Updates".

Version should be: beta_04-13-22_1649911391

**Comment by ArbenKarb** [comment] 2022-04-14 06:06
1. Upgraded to latest Beta;
2. After restart got "Node offline error"
3. Reinstalled BTCPayServer as advised
4. no errors

**Comment by TTK-199837** [comment] 2022-04-15 01:59
I did as ArbenKarb did... everything seemed to be working again, until I noticed lightning invoices were not showing a QR code or bolt11 invoice. When I go into BTCpay -> wallets -> lightning ->  Public node info, it indicates that that the local node is unavailable. Am I doing something wrong?

**Comment by tehelsper** [comment] 2022-04-15 02:07
@TTK-199837 No, you probably are not. I don't think the current setup automatically configures the LND node. You would need to add your node as a custom node. The "local" node referenced by BTCPay I think is the one their system sets up which is disabled so the device doesn't run two instances of lnd.

**Comment by TTK-199837** [comment] 2022-04-15 03:39
> @TTK-199837 No, you probably are not. I don't think the current setup automatically configures the LND node. You would need to add your node as a custom node. The "local" node referenced by BTCPay I think is the one their system sets up which is disabled so the device doesn't run two instances of lnd.
> 
> Edit: I've found a way to make the "Internal Node" in BTCPay refer to the local LND instance. This will be available next release.

Great... struggling to figure out how to get this working again. Thanks!

**Comment by tehelsper** [comment] 2022-05-21 16:52
Should be resolved in latest release.

**Closed by tehelsper** 2022-05-21 16:52 UTC
