### ISSUE TITLE
Mynode version 0.2.13 - Caravan always gives network error

### ISSUE THREAD

**Issue by imacfan** [mynodebtc/mynode#375] opened 2020-07-31 03:21 UTC
Access wallet screen at: http://192.168.1.199:3020/#/wallet

Quorum: 2 of 3
Address Type: P2WSH
Network: main
Bitcoin Client: Private
URL: http://192.168.1.199:8334
Username: mynode
Password: [Insert RPC Password from the Bitcoin page]

Network Error

Tried https as well..same issue

**Comment by tehelsper** [comment] 2020-08-01 02:34
I was not able to reproduce this. The URL definitely needs to be HTTPS. Have you tried opening http://192.168.1.199:8334 in your browser and accepting the certificate?

**Comment by imacfan** [comment] 2020-08-01 04:23
Ok. On Mac connection is successful on Safari. 
Safari however doesn't support HW wallets. 
Chrome always give https error. Need to figure out how to enable self signed certificate on Chrome on Mac.

**Comment by bucko13** [comment] 2020-08-02 21:04
Is "allow insecure localhost" enabled in your browser?
chrome://flags/#allow-insecure-localhost

**Comment by tehelsper** [comment] 2020-08-02 22:56
That may help, but I tested in chrome and spent a LOT of time trying to prevent requiring that setting.

Can you run this command and share the output? It's the proxy service for btc rpc requests.

sudo systemctl status corsproxy_btcrpc.service

Finally, what is the error in chrome console when it says connection failed?

**Comment by imacfan** [comment] 2020-08-03 03:22
Ok.. finally this is resolved in Chrome on MacOS. 

Mac had multiple certificates (of Mynode) stored in KeyChain. 

I had to remove all of them and kept only recent one. 

In Chrome - manage SSL certificates, choose the recent certificate.

**Comment by tehelsper** [comment] 2020-08-03 03:36
Good to know. Thanks!

**Comment by TheTotalConnector** [comment] 2020-08-03 15:29
> Access wallet screen at: http://192.168.1.199:3020/#/wallet
> 
> Quorum: 2 of 3
> Address Type: P2WSH
> Network: main
> Bitcoin Client: Private
> URL: http://192.168.1.199:8334
> Username: mynode
> Password: [Insert RPC Password from the Bitcoin page]
> 
> Network Error
> 
> Tried https as well..same issue

____________
I have had the same issue, unfortunately again (since it had been working previously- before the latest mynode update). 
I tested it on all browsers, while being home on my local network. 
Address-type: P2WSH 
URL: https://local IP:8334
Username: mynode
PW: RPC from Bitcoin page

Nothing works. Network Error. 
I even tested accessing Caravan "neutral": https://unchained-capital.github.io/caravan/#/wallet
and via mynode-dashboard. 
Please, can you look into any hidden issues.

**Comment by TheTotalConnector** [comment] 2020-08-03 15:29
Thanks

**Comment by tehelsper** [comment] 2020-08-03 22:42
Can you run this command and share the output? It's the proxy service for btc rpc requests.

sudo systemctl status corsproxy_btcrpc.service

What is the error in chrome console when it says connection failed?

**Comment by TheTotalConnector** [comment] 2020-08-04 06:18
Layman question: please, can you tell  how and where exactly i can run this command? -- Sent from my Android phone with GMX Mail. Please excuse my brevity.On 8/4/20, 00:43 Taylor Helsper <notifications@github.com> wrote:

   
  Can you run this command and share the output? It's the proxy service for btc rpc requests. 
  sudo systemctl status corsproxy_btcrpc.service 
  What is the error in chrome console when it says connection failed?

**Comment by Jacksper13** [comment] 2021-05-03 08:38
@tehelsper I'd close this - caravan has been updated multiple times since this issue

**Comment by tehelsper** [comment] 2021-05-03 23:36
Closing - all related apps and proxies have been updated.

**Closed** 2021-05-03 23:36 UTC
